<?php
/**
 * doc-query.phtml
 * @author Jeff Peralta - jaydocperalta@gmail.com
 * @copyright Copyright (c) 2017.
 * Date: Tue, 12 Sep 2017
 * Time: 12:54:59 +0800
 *
 * LICENSE : this file is the exclusive property. No unauthorized copy or modification is allowed.
 *
 */

?>
<html>
    <body>
    <?php
        if(is_array($this->results)){
            print_r($this->results);
        } else {
            echo $this->results;
        }
    ?>
    </body>
</html>